'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Api}=require('teleproto'),bi=require('big-integer'),{run}=require('../dist/nodes/NnaMediaReader/reader');
const c={apiId:12345,apiHash:'a'.repeat(32),sessionString:'1'+'A'.repeat(352),expectedUserId:'77',expectedUsername:'owner',allowedGroupId:'-1001417810280',allowedGroupUsername:'nnasoulsdiscuss',allowedTopicIds:'10'};
const scope={ownerId:'77',groupId:'-1001417810280',groupName:'Discussion'},request={action:'audio',url:'https://t.me/c/1417810280/10/123'};
function fake(patch={}){let downloaded=0,closed=false;const m=new Api.Message({id:123,date:1790400000,message:'caption',peerId:new Api.PeerChannel({channelId:bi(1417810280)}),fromId:new Api.PeerUser({userId:bi(77)}),replyTo:new Api.MessageReplyHeader({forumTopic:true,replyToMsgId:10}),media:{document:{size:128,mimeType:'audio/ogg',attributes:[{className:'DocumentAttributeAudio',duration:30,voice:true}]}},...patch});m.getSender=async()=>new Api.User({id:bi(77),firstName:'Owner'});const client={connect:async()=>{},destroy:async()=>{closed=true;},getMe:async()=>new Api.User({id:bi(77),username:'owner'}),getEntity:async()=>new Api.Channel({id:bi(1417810280),megagroup:true,forum:true}),getInputEntity:async()=>new Api.InputPeerChannel({channelId:bi(1417810280),accessHash:bi(1)}),invoke:async()=>({count:1,topics:[{className:'ForumTopic',id:10,title:'Daily'}]}),getMessages:async()=>[m],downloadMedia:async()=>{downloaded++;return Buffer.concat([Buffer.from('OggS'),Buffer.alloc(124)]);}};return {client,flags:()=>({downloaded,closed}),deps:{createClient:async()=>client}};}
test('audio reader returns private bytes only for verified group/topic and true audio',async()=>{const f=fake(),r=await run(c,scope,request,f.deps);assert.equal(r.status,'audio_downloaded');assert.equal(r.metadata.sender,'Owner');assert.equal(r.metadata.duration_seconds,30);assert.equal(r.mimeType,'audio/ogg');assert.equal(r.audioBytes.length,128);assert.deepEqual(f.flags(),{downloaded:1,closed:true});});
test('audio reader rejects foreign group, wrong topic, deleted post and video before download',async()=>{for(const patch of [{peerId:new Api.PeerChannel({channelId:bi(999)})},{replyTo:new Api.MessageReplyHeader({forumTopic:true,replyToMsgId:99})},{id:124},{media:{document:{size:128,mimeType:'video/mp4',attributes:[{className:'DocumentAttributeVideo',duration:30}]}}}]){const f=fake(patch);await assert.rejects(run(c,scope,request,f.deps),/NNA_READER_AUDIO_/);assert.equal(f.flags().downloaded,0);assert(f.flags().closed);}});
test('audio reader disallows oversized and overlong recordings without truncation',async()=>{for(const [size,duration] of [[22000000,30],[128,1201]]){const f=fake({media:{document:{size,mimeType:'audio/ogg',attributes:[{className:'DocumentAttributeAudio',duration}]}}});await assert.rejects(run(c,scope,request,f.deps),/NNA_AUDIO_(SIZE|DURATION)/);assert.equal(f.flags().downloaded,0);}});
test('audio reader resolves topic from direct post URL and cannot cross configured group',async()=>{const f=fake();const r=await run(c,scope,{action:'audio',url:'https://t.me/nnasoulsdiscuss/123'},f.deps);assert.equal(r.metadata.topic_id,10);let connected=false;await assert.rejects(run(c,scope,{action:'audio',url:'https://t.me/c/2550760684/123'},{createClient:()=>{connected=true;}}),/SCOPE/);assert.equal(connected,false);});
test('audio transport errors remain sanitized and client closes',async()=>{const f=fake();f.client.downloadMedia=async()=>{throw Error('secret-session-value');};await assert.rejects(run(c,scope,request,f.deps),e=>e.message==='NNA_READER_UNAVAILABLE');assert(f.flags().closed);});
