'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Api}=require('teleproto'),bigInt=require('big-integer');
const {imageReactionEvent}=require('../dist/nodes/NnaTelegramSender/image-reactions');
const {runOperation}=require('../dist/nodes/NnaTelegramSender/sender');
const now=Date.parse('2026-09-25T00:00:00Z');
const cfg={imageGroupId:'-1001234567',imageTopicId:10,imageEmojiIds:'111,222,333',imageStartHour:4,imageEndHour:10,imageActivatedAt:'2026-09-24T00:00:00Z'};
const c={apiId:12345,apiHash:'a'.repeat(32),sessionString:'1'+'A'.repeat(352),expectedUserId:'12345',allowedGroupId:'-1001234567',allowedGroupUsername:'example_group',allowedTopicIds:'20'};
const event=()=>({update_id:1,message:{message_id:30,date:now/1000,chat:{id:-1001234567,type:'supergroup'},message_thread_id:10,is_topic_message:true,photo:[{file_id:'example'}]}});
const params=()=>({...cfg,update:event(),claimValidated:true,claimRequestKey:'image:-1001234567:30'});
function fake(){let own=[],writes=0;const peer=new Api.PeerChannel({channelId:bigInt(1234567)});const m=new Api.Message({id:30,date:now/1000,peerId:peer,message:'',media:new Api.MessageMediaPhoto({}),replyTo:new Api.MessageReplyHeader({forumTopic:true,replyToTopId:10,replyToMsgId:10})});
const client={connect:async()=>{},destroy:async()=>{},getMe:async()=>new Api.User({id:bigInt(12345)}),getEntity:async()=>new Api.Channel({id:bigInt(1234567),megagroup:true,forum:true}),getInputEntity:async()=>new Api.InputPeerChannel({channelId:bigInt(1234567),accessHash:bigInt(1)}),getMessages:async()=>{m.reactions=own.length?{results:own.map(reaction=>({reaction,count:1}))}:undefined;return [m];},invoke:async r=>{
 if(r.className==='channels.GetFullChannel')return {fullChat:{}};
 if(r.className==='messages.GetForumTopicsByID')return {topics:[{className:'ForumTopic',id:10,title:'Morning'}]};
 if(r.className==='messages.GetCustomEmojiDocuments')return ['111','222','333'].map(id=>({className:'Document',id:bigInt(id),attributes:[{className:'DocumentAttributeCustomEmoji'}]}));
 if(r.className==='messages.GetMessageReactionsList')return {reactions:own.map(reaction=>({peerId:new Api.PeerUser({userId:bigInt(12345)}),reaction}))};
 if(r.className==='messages.SendReaction'){writes++;own=r.reaction;return {};}
 throw Error('Unexpected RPC');
 }};return {client,m,get writes(){return writes;},set own(v){own=v;}};}
test('India window boundaries and activate/date freshness are enforced',()=>{for(const [utc,ok] of [['2026-09-24T22:29:59Z',false],['2026-09-24T22:30:00Z',true],['2026-09-25T04:29:59Z',true],['2026-09-25T04:30:00Z',false]]){const u=event();u.message.date=Date.parse(utc)/1000;assert.equal(!!imageReactionEvent(u,cfg,Date.parse(utc)),ok);}assert.equal(imageReactionEvent(event(),cfg,now+1800001),null);assert.equal(imageReactionEvent(event(),{...cfg,imageActivatedAt:new Date(now+1).toISOString()},now),null);});
test('only the configured topic and original image messages qualify',()=>{for(const edit of [m=>m.message_thread_id=20,m=>m.chat.id=-1002222222,m=>delete m.photo,m=>m.is_topic_message=false]){const u=event();edit(u.message);assert.equal(imageReactionEvent(u,cfg,now),null);}const u=event();u.edited_message=u.message;assert.equal(imageReactionEvent(u,cfg,now),null);const d=event();delete d.message.photo;d.message.document={mime_type:'image/png'};assert.ok(imageReactionEvent(d,cfg,now));d.message.document.mime_type='application/pdf';assert.equal(imageReactionEvent(d,cfg,now),null);});
test('image proof sends exactly three and repeated invocation is idempotent',async()=>{const f=fake();const r=await runOperation('reactToScheduledImage',c,params(),{now,createClient:async()=>f.client});assert.equal(r.status,'reacted');assert.deepEqual(r.customEmojiIds,['111','222','333']);assert.equal((await runOperation('reactToScheduledImage',c,params(),{now,createClient:async()=>f.client})).status,'already_present');assert.equal(f.writes,1);});
test('read-only scope check never writes',async()=>{const f=fake();assert.equal((await runOperation('inspectImageReactionScope',c,cfg,{now,createClient:async()=>f.client})).verified,true);assert.equal(f.writes,0);});
test('forged claim and wrong source cannot write',async()=>{let connected=false;await assert.rejects(runOperation('reactToScheduledImage',c,{...params(),claimRequestKey:'wrong'},{now,createClient:async()=>{connected=true;return fake().client;}}),/CLAIM/);assert.equal(connected,false);for(const change of [m=>m.date--,m=>m.media=undefined,m=>m.editDate=1,m=>m.replyTo.replyToTopId=20]){const f=fake();change(f.m);await assert.rejects(runOperation('reactToScheduledImage',c,params(),{now,createClient:async()=>f.client}),/SOURCE/);assert.equal(f.writes,0);}});
test('existing unrelated reactions stay untouched and ambiguous writes are not retried',async()=>{const f=fake();f.own=[new Api.ReactionEmoji({emoticon:'🙏'})];await assert.rejects(runOperation('reactToScheduledImage',c,params(),{now,createClient:async()=>f.client}),/EXISTING_REACTIONS/);assert.equal(f.writes,0);const g=fake(),invoke=g.client.invoke;let writes=0;g.client.invoke=async r=>{if(r.className==='messages.SendReaction'){writes++;throw Error('network');}return invoke(r);};await assert.rejects(runOperation('reactToScheduledImage',c,params(),{now,createClient:async()=>g.client}),/UNCONFIRMED/);assert.equal(writes,1);});
