'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Service}=require('../dist/nodes/NnaPollStudio/service');
const c={apiId:1,apiHash:'a'.repeat(32),sessionString:'1AAAA',expectedUserId:'42',allowedGroupId:'-1001234500000',allowedGroupUsername:'testgroup',allowedTopicIds:'10'};
const scope={botId:'99',botUsername:'test_bot',operatorIds:['42','43'],groups:[{id:c.allowedGroupId,title:'Group'}],defaultTargets:[]};
const msg=(id,text,extra={})=>({update_id:id,message:{message_id:id,date:Math.floor(Date.now()/1000),chat:{id:42,type:'private'},from:{id:42,is_bot:false},text,...extra}});
const payload=(label='Next',data='tpl:42:list:3')=>({event:msg(1,'/templates'),operatorId:'42',chatId:'42',text:'Choose',entities:[],keyboard:{rows:[{row:{buttons:[{text:label,additionalFields:{callback_data:data}}]}}]}});
test('both bot keyboards allow native hide and reopen without removing saved actions',async t=>{const {s,calls}=setup(t);await s.renderLegacy(payload());assert.equal(calls.at(-1).body.reply_markup.is_persistent,false);assert.equal(calls.at(-1).body.reply_markup.one_time_keyboard,false);assert(s.store.read('legacy_ui_42').keys.Next);await s.handle(msg(2,'/poll'));assert.equal(calls.at(-1).body.reply_markup.is_persistent,false);});
function setup(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'nna-keyboard-')),calls=[];t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const ctx={helpers:{httpRequest:async r=>{const method=r.url.split('/').at(-1);calls.push({method,body:r.body});return {ok:true,result:method==='getMe'?{id:99,username:'test_bot'}:{message_id:100+calls.length,date:Math.floor(Date.now()/1000),from:{id:99,is_bot:true},chat:{id:Number(r.body.chat_id),type:'private'},text:r.body.text,entities:r.body.entities||[]}};}}};return {s:new Service(ctx,c,{accessToken:'99:test'},scope,{root}),calls,root};}
test('nested pagination, edit and back replace keys, retain owner and never acknowledge synthetic callback',async t=>{const {s,calls}=setup(t);assert.equal(await s.renderLegacy(payload()),null);let r=await s.handle(msg(2,'Next'));assert.equal(r.handled,false);assert.equal(r.event.callback_query.data,'tpl:42:list:3');assert.equal(r.event.callback_query.id,'');assert.equal(r.event.callback_query.from.id,42);assert.equal(r.event.callback_query.message.from.id,99);assert.equal(calls.filter(x=>x.method==='answerCallbackQuery').length,0);await s.renderLegacy({...payload('Edit','tpl:42:edit:code'),event:r.event});r=await s.handle(msg(3,'Edit'));assert.equal(r.event.callback_query.data,'tpl:42:edit:code');assert.equal((await s.handle(msg(4,'Next'))).event.message.text,'Next');});
test('private media preview exposes confirm and subsequent final approval remains distinct',async t=>{const {s,calls}=setup(t);const p={...payload(),buttons:[{label:'Confirm draft',data:'mp:42:abcdef:confirm'}]};await s.renderLegacy(p,true);assert(calls.at(-1).body.reply_markup.keyboard[0][0].text==='Confirm draft');assert.equal((await s.handle(msg(2,'Confirm draft'))).event.callback_query.data,'mp:42:abcdef:confirm');await s.renderLegacy(payload('Publish','mp:42:abcdef:publish'));assert.equal((await s.handle(msg(3,'Publish'))).event.callback_query.data,'mp:42:abcdef:publish');assert.equal(calls.some(x=>/sendPhoto|sendVideo/.test(x.method)),false);});
test('unauthorized, forwarded, stale and cross-owner messages never resolve saved actions',async t=>{const {s}=setup(t);await s.renderLegacy(payload());for(const extra of [{from:{id:44,is_bot:false}},{forward_origin:{type:'user'}},{date:1},{chat:{id:43,type:'private'},from:{id:43,is_bot:false}}]){const r=await s.handle(msg(2,'Next',extra));assert.equal(r.event.callback_query,undefined);}s.store.change('legacy_ui_42',x=>({...x,expiresAt:1}));assert.equal((await s.handle(msg(3,'Next'))).event.callback_query,undefined);});
test('group menus and history force reply remain chat UI, invalid callback ownership cannot create keyboard',async t=>{const {s,calls}=setup(t);for(const p of [{...payload(),historyPrompt:true},{...payload(),event:msg(1,'x',{chat:{id:Number(c.allowedGroupId),type:'supergroup'}}),chatId:c.allowedGroupId},payload('Wrong','tpl:43:list:')])assert.equal(await s.renderLegacy(p),p);assert.equal(calls.length,0);});
test('main menu and poll screens clear nested controls, state survives service restart',async t=>{const {s,calls,root}=setup(t);await s.renderLegacy(payload());const again=new Service(s.ctx,c,s.b,scope,{root});assert.equal((await again.handle(msg(2,'Next'))).event.callback_query.data,'tpl:42:list:3');await s.handle(msg(3,'🏠 Main Menu'));assert.equal(s.store.read('legacy_ui_42'),null);await s.renderLegacy(payload());await s.handle(msg(4,'/poll'));assert.equal(s.store.read('legacy_ui_42'),null);assert(calls.at(-1).body.reply_markup.keyboard.flat().some(x=>x.text.includes('Quiz')));});
test('template exact text and custom emoji entities survive bottom-keyboard preview',async t=>{const {s,calls}=setup(t);const p={...payload(),text:'Hi 🔥',entities:[{type:'custom_emoji',offset:3,length:2,custom_emoji_id:'12345'}]};await s.renderLegacy(p);assert.deepEqual(calls.at(-1).body.entities,p.entities);assert.equal(calls.at(-1).body.text,p.text);});
test('ambiguous duplicate labels keep existing inline controls instead of dispatching wrong action',async t=>{const {s,calls}=setup(t);const p=payload();p.keyboard.rows.push({row:{buttons:[{text:'Next',additionalFields:{callback_data:'tpl:42:edit:3'}}]}});assert.equal(await s.renderLegacy(p),p);assert.equal(calls.length,0);});
