'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{Api}=require('teleproto'),bigInt=require('big-integer'),{validateLive,liveRandomId,scheduleLive}=require('../dist/nodes/NnaTelegramSender/live-schedule');
const now=Date.now(),c={expectedUserId:'42',allowedGroupId:'-1001234500000'};
function params(){return {config:{reviewGroupId:'-1009876500000',botId:'99',operatorIds:['42'],liveTargets:[{groupId:c.allowedGroupId}]},delivery:{mode:'live',claimValidated:true,operatorId:'42',chatId:'42',topicId:0,revision:'123',requestKey:'live:42:42:0:123',approvedAt:new Date(now).toISOString(),update:{update_id:124,callback_query:{from:{id:42,is_bot:false},data:'lv:42:123:publish',message:{chat:{id:42,type:'private'},from:{id:99,is_bot:true}}}},targetGroupId:c.allowedGroupId,title:'அன்பும் அறமும்',liveAt:Math.floor(now/1000)+3600,rtmp:false}};}
function mock(p,opts={}){let writes=0,created=false,request;const call={className:'GroupCall',id:bigInt(88),accessHash:bigInt(1),title:p.delivery.title,scheduleDate:p.delivery.liveAt};return {get writes(){return writes;},get request(){return request;},getEntity:async n=>new Api.Channel({id:bigInt(String(n).slice(4)),megagroup:true,forum:true,title:'Test',photo:new Api.ChatPhotoEmpty(),date:0}),getInputEntity:async g=>new Api.InputPeerChannel({channelId:g.id,accessHash:bigInt(1)}),invoke:async x=>{
 if(x.className==='channels.GetParticipant')return {participant:{className:'ChannelParticipantAdmin',adminRights:{manageCall:!opts.noAdmin}}};
 if(x.className==='channels.GetFullChannel')return {fullChat:{call:created||opts.existing?new Api.InputGroupCall({id:call.id,accessHash:call.accessHash}):undefined}};
 if(x.className==='phone.GetGroupCall')return {call:{...call,...(opts.mismatch?{title:'different'}:{})}};
 assert.equal(x.className,'phone.CreateGroupCall');writes++;request=x;if(opts.uncertain)throw Error('network');created=true;return {updates:[{call}]};}};}
test('scheduled native Live verifies call without starting it or exposing access hash',async()=>{const p=params(),m=mock(p),r=await scheduleLive(m,c,p,x=>x,now);assert.equal(r.status,'live_scheduled');assert.equal(r.liveAt,p.delivery.liveAt);assert.equal(r.autoStart,false);assert.equal(r.accessHash,undefined);assert.equal(m.writes,1);assert.equal(m.request.rtmpStream,false);assert.equal(m.request.randomId,liveRandomId('42',p.delivery.requestKey));});
test('actor, callback, chat, expiry, destination, title and date guards reject',()=>{for(const mutate of [p=>p.delivery.update.callback_query.from.id=43,p=>p.delivery.update.callback_query.data='lv:42:999:publish',p=>p.delivery.update.callback_query.message.chat.id=43,p=>p.delivery.claimValidated=false,p=>p.delivery.targetGroupId='-1001111111111',p=>p.delivery.approvedAt=new Date(now-700000).toISOString(),p=>p.delivery.title='bad\ntitle',p=>p.delivery.title='a'.repeat(129),p=>p.delivery.liveAt=Math.floor(now/1000)+1,p=>p.delivery.liveAt=Math.floor(now/1000)+9*86400,p=>p.delivery.rtmp=true]){const p=params();mutate(p);assert.throws(()=>validateLive(c,p,now),/NNA_LIVE_/);}});
test('existing Live and missing admin rights prevent all writes',async()=>{for(const opts of [{existing:true},{noAdmin:true}]){const p=params(),m=mock(p,opts);await assert.rejects(scheduleLive(m,c,p,x=>x,now),/NNA_LIVE_(ADMIN_REQUIRED|ALREADY_EXISTS)/);assert.equal(m.writes,0);}});
test('uncertain create and mismatched readback never retry or report success',async()=>{for(const opts of [{uncertain:true},{mismatch:true}]){const p=params(),m=mock(p,opts);await assert.rejects(scheduleLive(m,c,p,x=>x,now),/DELIVERY_UNCONFIRMED/);assert.equal(m.writes,1);}});
