'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),{Api}=require('teleproto'),bi=require('big-integer');
const {run}=require('../dist/nodes/NnaMediaReader/reader');
const c={apiId:12345,apiHash:'a'.repeat(32),sessionString:'1'+'A'.repeat(352),expectedUserId:'77',expectedUsername:'owner',allowedGroupId:'-10011111',allowedGroupUsername:'example_group',allowedTopicIds:'10'};
const scope={ownerId:'77',groupId:'-10022222',groupName:'Media'};
const query={action:'posts',topicId:12,startDate:'2026-09-26',endDate:'2026-09-26'};
const msg=(id,patch={})=>new Api.Message({id,date:Date.parse('2026-09-26T10:00:00Z')/1000,message:'தமிழ் caption #Peace',peerId:new Api.PeerChannel({channelId:bi(22222)}),fromId:new Api.PeerUser({userId:bi(77)}),replyTo:new Api.MessageReplyHeader({forumTopic:true,replyToMsgId:12}),...patch});
function fake(pages=[]){const calls=[],client={connect:async()=>{},destroy:async()=>{},getMe:async()=>new Api.User({id:bi(77),username:'owner'}),getEntity:async()=>new Api.Channel({id:bi(22222),megagroup:true,forum:true}),getInputEntity:async()=>new Api.InputPeerChannel({channelId:bi(22222),accessHash:bi(1)}),invoke:async q=>{calls.push(q);if(q.className==='messages.GetForumTopics')return {count:2,topics:[{className:'ForumTopic',id:1,title:'General',closed:true},{className:'ForumTopic',id:12,title:'Spiritual'}]};assert.ok(['messages.GetReplies','messages.GetHistory'].includes(q.className));return {messages:pages.shift()||[],users:[new Api.User({id:bi(77),firstName:'Owner'})]};},getMessages:async()=>[],downloadMedia:async()=>Buffer.from([255,216,255,1])};return {client,calls,deps:{createClient:async()=>client}};}
test('reader rejects scope escalation and malformed requests before connecting',async()=>{for(const [s,r] of [[{...scope,ownerId:'88'},query],[scope,{...query,groupId:'-100999'}],[scope,{...query,startDate:'2026-02-30'}],[scope,{action:'images',topicId:12,messageIds:[4,4]}],[scope,{action:'images',topicId:12,messageIds:[1,2,3,4]}],[scope,{action:'publish'}]]){let touched=false;await assert.rejects(run(c,s,r,{createClient:()=>{touched=true;}}),/NNA_READER_/);assert.equal(touched,false);}});
test('topics include closed topics and do not post',async()=>{const f=fake();const r=await run(c,scope,{action:'topics'},f.deps);assert.equal(r.topics.length,2);assert.equal(r.read_only,true);assert.equal(f.calls.length,1);});
test('caption report joins album pages and preserves IDs, private links and full text',async()=>{const media={className:'MessageMediaPhoto'};const f=fake([[msg(102,{media,groupedId:bi(33),message:''})],[msg(101,{media,groupedId:bi(33)})],[]]);const r=await run(c,scope,query,f.deps);assert.equal(r.complete,true);assert.equal(r.total_posts,1);assert.equal(r.total_messages,2);assert.deepEqual(r.posts[0].image_message_ids,[101,102]);assert.equal(r.posts[0].url,'https://t.me/c/22222/12/101');assert.match(r.posts[0].text,/தமிழ்/);});
test('caption search retains complete coverage totals and does not invent visual matches',async()=>{const f=fake([[msg(5),msg(4,{message:'another'})],[]]);const r=await run(c,scope,{...query,query:'#peace'},f.deps);assert.equal(r.total_posts,2);assert.equal(r.matched_posts,1);assert.equal(r.posts.length,1);});
test('General and whole-group queries use history and filter General explicitly',async()=>{for(const topicId of [0,1]){const f=fake([[msg(5),msg(4,{replyTo:undefined})],[]]);const r=await run(c,scope,{...query,topicId},f.deps);assert.equal(r.total_posts,topicId?1:2);assert.equal(f.calls[1].className,'messages.GetHistory');}});
test('history rejects foreign data, wrong identity and stale cursors',async()=>{for(const patch of [{peerId:new Api.PeerChannel({channelId:bi(999)})},{replyTo:new Api.MessageReplyHeader({forumTopic:true,replyToMsgId:99})}]){const f=fake([[msg(3,patch)]]);await assert.rejects(run(c,scope,query,f.deps),/WRONG_/);}const f=fake([[msg(3)],[msg(3)]]);await assert.rejects(run(c,scope,query,f.deps),/CURSOR/);const g=fake();g.client.getMe=async()=>new Api.User({id:bi(99)});await assert.rejects(run(c,scope,{action:'topics'},g.deps),/IDENTITY/);});
test('images are verified before any download and videos never download',async()=>{for(const m of [msg(5),msg(5,{media:{className:'MessageMediaDocument',document:{mimeType:'video/mp4',attributes:[]}}}),msg(5,{replyTo:undefined,media:{className:'MessageMediaPhoto'}})]){const f=fake();f.client.getMessages=async()=>[m];f.client.downloadMedia=async()=>{throw Error('SHOULD_NOT_DOWNLOAD');};await assert.rejects(run(c,scope,{action:'images',topicId:12,messageIds:[5]},f.deps),/NNA_READER_(NOT_IMAGE|PHOTO_SCOPE)/);}});
test('photo bytes use largest bounded size and preserve request order',async()=>{const f=fake(),photo=id=>msg(id,{media:{className:'MessageMediaPhoto',photo:{sizes:[{className:'PhotoSize',type:'x',size:500,w:800,h:800},{className:'PhotoSize',type:'y',size:700,w:1280,h:1280}]}}});f.client.getMessages=async()=>[photo(7),photo(5)];f.client.downloadMedia=async(m,opts)=>{assert.equal(opts.thumb,'y');return Buffer.from([255,216,255,m.id]);};const r=await run(c,scope,{action:'images',topicId:12,messageIds:[5,7]},f.deps);assert.deepEqual(r.images.map(i=>i.message_id),[5,7]);assert.ok(r.images.every(i=>i.mimeType==='image/jpeg'));assert.ok(!JSON.stringify(r).includes(c.sessionString));});
test('RPC errors do not leak secrets',async()=>{const f=fake();f.client.invoke=async()=>{throw Error('private token');};await assert.rejects(run(c,scope,{action:'topics'},f.deps),e=>e.message==='NNA_READER_UNAVAILABLE');});

require("node:test").test("all registered n8n nodes load with valid descriptions",()=>{const assert=require("node:assert/strict");for(const path of require("../package.json").n8n.nodes){const mod=require("../"+path);const Node=Object.values(mod)[0];const node=new Node();assert.ok(node.description.name);assert.ok(Array.isArray(node.description.properties));}});
