'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),{Api}=require('teleproto'),bigInt=require('big-integer'),{parsePollText}=require('../dist/nodes/NnaTelegramSender/poll-content'),{validatePoll,pollMatches,publishPoll}=require('../dist/nodes/NnaTelegramSender/poll-publish');
const now=Date.now(),c={expectedUserId:'42',allowedGroupId:'-1001234500000'};
function params(anonymous=true){const sourceText='உங்களுக்கு வசதியான நேரம்?\nA) காலை\nB) மாலை';return {config:{reviewGroupId:'-1009876500000',botId:'99',operatorIds:['42'],pollShuffle:true,pollTargets:[{groupId:c.allowedGroupId,topicId:10}]},delivery:{mode:'poll',claimValidated:true,operatorId:'42',chatId:'42',topicId:0,revision:'123',requestKey:'poll:42:42:0:123',approvedAt:new Date(now).toISOString(),update:{update_id:124,callback_query:{from:{id:42,is_bot:false},data:'pp:42:123:publish',message:{chat:{id:42,type:'private'},from:{id:99,is_bot:true}}}},targetGroupId:c.allowedGroupId,targetTopicId:10,anonymous,sourceText,sourceEntities:[],poll:parsePollText(sourceText)}};}
function mock(p,fail=false){let writes=0,posted,request;return {get writes(){return writes;},get request(){return request;},getEntity:async n=>new Api.Channel({id:bigInt(String(n).slice(4)),megagroup:true,forum:true,title:'Test',photo:new Api.ChatPhotoEmpty(),date:0}),getInputEntity:async g=>new Api.InputPeerChannel({channelId:g.id,accessHash:bigInt(1)}),getMessages:async()=>[posted],invoke:async x=>{if(x.className==='messages.GetForumTopicsByID')return {topics:[{className:'ForumTopic',id:10}]};if(x.className==='help.GetAppConfig')return {config:{value:[{key:'poll_answers_max',value:{value:12}}]}};assert.equal(x.className,'messages.SendMedia');writes++;request=x;if(fail)throw Error('network');posted={className:'Message',id:88,out:true,fromId:new Api.PeerUser({userId:bigInt(42)}),peerId:new Api.PeerChannel({channelId:bigInt(1234500000)}),replyTo:{replyToTopId:10},media:new Api.MessageMediaPoll({poll:x.media.poll,results:new Api.PollResults({})})};return {updates:[{className:'UpdateMessageID',id:88,randomId:x.randomId}]};}};}
test('ABC, numbers and bullets strip only labels and preserve Tamil answer content',()=>{for(const labels of [['A)','B)'],['1.','2.'],['•','•'],['-','-']]){const p=parsePollText('கேள்வி?\n'+labels[0]+' ஆம்\n'+labels[1]+' இல்லை');assert.equal(p.question.text,'கேள்வி?');assert.deepEqual(p.answers.map(a=>a.text),['ஆம்','இல்லை']);}});
test('custom emoji offset survives trimmed labels and astral characters',()=>{const t='🌿 கேள்வி?\nA) 🙏 ஆம்\nB) இல்லை',at=t.indexOf('🙏'),p=parsePollText(t,[{type:'custom_emoji',offset:at,length:2,custom_emoji_id:'123'}]);assert.equal(p.answers[0].entities[0].offset,0);});
test('ambiguous labels, missing questions, duplicates and excess length reject',()=>{for(const t of ['A) one\nB) two','Question\nA) one\nC) two','Question\n1) one\n• two','Question\nA) one\nB) ONE','x'.repeat(301)+'\nA) one\nB) two','Question\nA) '+ 'x'.repeat(101)+'\nB) two'])assert.throws(()=>parsePollText(t),/POLL_/);});
test('anonymous and public native polls lock all requested defaults and send personally',async()=>{for(const anonymous of [true,false]){const p=params(anonymous),m=mock(p),r=await publishPoll(m,c,p,x=>x,now);assert.equal(r.anonymous,anonymous);assert.equal(r.sentMessageId,88);const poll=m.request.media.poll;assert.equal(poll.publicVoters,!anonymous);assert.equal(poll.shuffleAnswers,true);for(const key of ['multipleChoice','quiz','openAnswers'])assert.equal(poll[key],false);assert.equal(poll.closeDate,undefined);assert.equal(poll.closePeriod,undefined);assert.equal(m.request.media.correctAnswers,undefined);assert.equal(m.request.sendAs.className,'InputPeerSelf');assert.equal(m.writes,1);}});
test('forged actor, changed question/settings/destination and stale approval cannot send',()=>{for(const fn of [p=>p.delivery.update.callback_query.from.id=43,p=>p.delivery.poll.answers[0].text='changed',p=>p.delivery.claimValidated=false,p=>p.config.pollShuffle=false,p=>p.delivery.targetTopicId=11,p=>p.delivery.approvedAt=new Date(now-700000).toISOString()]){const p=params();fn(p);assert.throws(()=>validatePoll(c,p,now),/NNA_POLL_/);}});
test('uncertain poll write is never retried or reported as success',async()=>{const p=params(),m=mock(p,true);await assert.rejects(publishPoll(m,c,p,x=>x,now),/DELIVERY_UNCONFIRMED/);assert.equal(m.writes,1);});
test('returned poll setting mismatch fails verification',async()=>{const p=params(),m=mock(p);await publishPoll(m,c,p,x=>x,now);const poll=m.request.media.poll;assert.equal(pollMatches(poll,p.delivery),true);poll.openAnswers=true;assert.equal(pollMatches(poll,p.delivery),false);});
