'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),bigInt=require('big-integer'),{Api}=require('teleproto');
const {Service,authenticate}=require('../dist/nodes/NnaPollStudio/service'),model=require('../dist/nodes/NnaPollStudio/model'),todo=require('../dist/nodes/NnaPollStudio/checklist'),{parsePollText}=require('../dist/nodes/NnaTelegramSender/poll-content');
const c={apiId:1,apiHash:'a'.repeat(32),sessionString:'1AAAA',expectedUserId:'42',expectedUsername:'nna_enthiran',allowedGroupId:'-1001234500000',allowedGroupUsername:'nnasoulsdiscuss',allowedTopicIds:'10'};
const scope={botId:'99',botUsername:'N_N_A_TestBot',operatorIds:['42','43'],groups:[{id:c.allowedGroupId,title:'Group'}],defaultTargets:[{groupId:c.allowedGroupId,topicId:10,title:'Daily'}]};
function draft(type='poll'){const sourceText=type==='checklist'?'Daily checklist\n1. Read\n2. Write':'Question?\nA) Yes\nB) No';return {owner:'42',sourceText,sourceEntities:[],poll:(type==='checklist'?todo.parse:parsePollText)(sourceText),settings:{...model.defaults(),type,correct:type==='quiz'?[1]:[]}};}
function message(id,text,extra={}){return {update_id:id,message:{message_id:id,date:Math.floor(Date.now()/1000),chat:{type:'private',id:42},from:{id:42,is_bot:false},text,...extra}};}
function mockClient(){let sent,posted;return {get sent(){return sent;},connect:async()=>{},destroy:async()=>{},getMe:async()=>({id:42,username:'nna_enthiran',premium:true}),getEntity:async()=>new Api.Channel({id:bigInt(1234500000),megagroup:true,forum:true,title:'Test',photo:new Api.ChatPhotoEmpty(),date:0}),getInputEntity:async g=>new Api.InputPeerChannel({channelId:g.id,accessHash:bigInt(1)}),getMessages:async()=>[posted],invoke:async x=>{if(x.className==='messages.GetForumTopicsByID')return {topics:[{className:'ForumTopic',id:10}]};sent=x;if(x.media.poll)x.media.poll.answers=x.media.poll.answers.map((a,i)=>a.className==='InputPollAnswer'?new Api.PollAnswer({text:a.text,option:Buffer.from([i])}):a);posted={id:88,out:true,fromId:new Api.PeerUser({userId:bigInt(42)}),peerId:new Api.PeerChannel({channelId:bigInt(1234500000)}),replyTo:{replyToTopId:10},message:x.message,media:x.media.poll?new Api.MessageMediaPoll({poll:x.media.poll,results:new Api.PollResults({solution:x.media.solution||'',results:(x.media.correctAnswers||[]).map(i=>({correct:true,option:Buffer.from([i])}))})}):new Api.MessageMediaToDo({todo:x.media.todo,completions:[]})};return {updates:[{className:'UpdateMessageID',id:88,randomId:x.randomId}]};}};}
function service(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'nna-studio-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const calls=[],client=mockClient(),ctx={helpers:{httpRequest:async r=>{const method=r.url.split('/').at(-1);calls.push({method,body:r.body});return {ok:true,result:method==='getMe'?{id:99,username:scope.botUsername}:true};}}};return {s:new Service(ctx,c,{accessToken:'99:test'},scope,{root,createClient:async()=>client}),calls,client,root};}
test('quiet poll publication preserves durable receipt and duplicate guard without a confirmation message',async t=>{const {s,calls}=service(t);s.scope.pollPublishConfirmation=false;let publishes=0;s.deps.publish=async()=>{publishes++;return {status:'sent',messageId:88,url:'https://t.me/c/1234500000/10/88'};};const receipt=await s.deliver('42',draft(),scope.defaultTargets[0],'quiet');assert.equal(receipt.status,'sent');assert.equal(s.store.read('send_quiet').status,'sent');assert.equal(calls.filter(x=>x.method==='sendMessage').length,0);assert.equal((await s.deliver('42',draft(),scope.defaultTargets[0],'quiet')).status,'duplicate');assert.equal(publishes,1);});
test('quiet poll scope retains default poll and quiz/checklist confirmations',async t=>{const {s,calls}=service(t);await s.deliver('42',draft(),scope.defaultTargets[0],'default');assert(calls.at(-1).body.text.includes('Poll வெளியிடப்பட்டது'));s.scope.pollPublishConfirmation=false;for(const type of ['quiz','checklist']){await s.deliver('42',draft(type),scope.defaultTargets[0],type);assert(calls.at(-1).body.text.includes(type==='quiz'?'Quiz வெளியிடப்பட்டது':'Checklist வெளியிடப்பட்டது'));}assert.equal(calls.filter(x=>x.method==='sendMessage').length,3);});
test('quiet poll failures remain visible and cannot be sent twice',async t=>{const {s,calls}=service(t);s.scope.pollPublishConfirmation=false;await s.saveTemplate(draft(),'quiet_test');calls.length=0;let attempts=0;s.deps.publish=async()=>{attempts++;throw Error('POLL_TOPIC_CLOSED');};const u=message(991,'quiet_test',{chat:{type:'supergroup',id:Number(c.allowedGroupId)},message_thread_id:10});const result=await s.handle(u);assert.equal(result.code,'POLL_TOPIC_CLOSED');assert.equal(s.store.read('send_u991').status,'uncertain');assert(calls.some(x=>x.method==='sendMessage'&&x.body.text.startsWith('⚠️')));assert.equal((await s.handle(u)).status,'duplicate');assert.equal(attempts,1);});
test('quiet poll scope rejects non-boolean settings',async t=>{const {s,root}=service(t);assert.throws(()=>new Service(s.ctx,c,s.b,{...scope,pollPublishConfirmation:'false'},{root}),/POLL_SCOPE/);});
test('native poll/quiz settings, correct indices and personal sender survive readback',async()=>{for(const type of ['poll','quiz']){const d=draft(type),client=mockClient();await model.publish(client,c,d,scope.defaultTargets[0],'key',p=>p);assert.equal(client.sent.sendAs.className,'InputPeerSelf');assert.equal(client.sent.media.poll.revotingDisabled,true);assert.deepEqual(client.sent.media.correctAnswers,type==='quiz'?[1]:undefined);d.settings.revote=true;await model.publish(client,c,d,scope.defaultTargets[0],'next',p=>p);assert.equal(client.sent.media.poll.revotingDisabled,false);}});
test('checklist publishes fresh native items with exact permission flags and sender',async()=>{for(const enabled of [false,true]){const d=draft('checklist');d.settings.othersAppend=enabled;d.settings.othersComplete=enabled;const client=mockClient();const r=await model.publish(client,c,d,scope.defaultTargets[0],'todo',p=>p);assert.equal(r.messageId,88);assert.equal(client.sent.media.className,'InputMediaTodo');assert.equal(client.sent.media.todo.othersCanComplete,enabled);assert.equal(client.sent.sendAs.className,'InputPeerSelf');assert.deepEqual(client.sent.media.todo.list.map(x=>x.id),[1,2]);}});
test('tampered content, invalid quiz, hide without timer and oversize checklist reject',()=>{const d=draft();d.poll.question.text='tampered';assert.throws(()=>model.validate(d));const q=draft('quiz');q.settings.correct=[0,1];assert.throws(()=>model.validate(q));assert.throws(()=>model.settings({hide:true}));assert.throws(()=>todo.parse('X\n2. Wrong'));assert.throws(()=>todo.parse('X\n1. '+'a'.repeat(101)));assert.throws(()=>todo.parse('X\n'+Array.from({length:31},(_,i)=>(i+1)+'. a').join('\n')));});
test('unauthorized, forwarded, wrong topic and channel-sender updates have no side effects',async t=>{const {s,calls}=service(t);for(const u of [message(1,'/poll',{from:{id:44,is_bot:false}}),message(2,'/poll',{forward_origin:{type:'user'}}),message(3,'/poll',{sender_chat:{id:12}})])assert.equal((await s.handle(u)).handled,false);assert.equal(calls.length,0);assert.equal(authenticate(message(4,'/poll',{date:0}),scope),null);});
test('wizard offers all three types, checklist settings, templates and persisted restart',async t=>{const {s,calls,root}=service(t);await s.handle(message(1,'/poll'));assert(calls.at(-1).body.reply_markup.keyboard.flat().some(x=>x.text.includes('Checklist')));await s.handle(message(2,'/checklist'));await s.handle(message(3,'Tasks\n1. Read\n2. Write'));let d=s.draft('42');assert.equal(d.settings.type,'checklist');assert.equal(d.stage,'settings');assert(calls.at(-1).body.text.includes('Complete')||calls.at(-1).body.text.includes('complete'));await s.handle(message(4,'/pollsave daily_tasks'));assert(s.templates().daily_tasks);const restarted=new Service(s.ctx,c,s.b,scope,{root});assert(restarted.templates().daily_tasks);assert.equal(restarted.targets().length,1);});
test('group keyword and replay guard send once from personal account only in enabled topic',async t=>{const {s,client}=service(t);await s.saveTemplate(draft(),'vote_test');const u=message(20,'vote_test',{chat:{type:'supergroup',id:Number(c.allowedGroupId)},message_thread_id:10});assert.equal((await s.handle(u)).status,'handled');assert.equal((await s.handle(u)).status,'duplicate');assert.equal(client.sent.sendAs.className,'InputPeerSelf');assert.equal((await s.handle(message(21,'vote_test',{chat:{type:'supergroup',id:Number(c.allowedGroupId)},message_thread_id:11}))).handled,false);});
test('stale callback and uncertain delivery cannot publish again',async t=>{const {s}=service(t);await s.handle(message(1,'/poll'));const u={update_id:2,callback_query:{id:'abc',data:'ps:42:12345678:type_poll',from:{id:42,is_bot:false},message:{chat:{id:42,type:'private'},from:{id:99,is_bot:true}}}};assert.equal((await s.handle(u)).code,'POLL_STALE');let writes=0;s.deps.publish=async()=>{writes++;throw Error('timeout');};await assert.rejects(s.deliver('42',draft(),scope.defaultTargets[0],'stable'));assert.equal((await s.deliver('42',draft(),scope.defaultTargets[0],'stable')).status,'duplicate');assert.equal(writes,1);});

test('collapsible bottom keyboard orders template actions last and routes legacy features',async t=>{const {s,calls}=service(t);await s.handle(message(30,'/menu'));const k=calls.at(-1).body.reply_markup;assert.equal(k.is_persistent,false);assert.deepEqual(k.keyboard.slice(-2).flat().map(x=>x.text),['📚 Templates','💾 புதிதாகச் சேமி','✏️ மாற்று']);const routed=await s.handle(message(31,'📄 User Chat History'));assert.equal(routed.handled,false);assert.equal(routed.event.message.text,'/history');await s.handle(message(32,'🗳️ Poll / Quiz / Checklist'));await s.handle(message(33,'☑️ Checklist'));assert.equal(s.draft('42').settings.type,'checklist');await s.handle(message(34,'🏠 Main Menu'));assert.equal(s.draft('42').active,false);});
test('group slash command verifies current admin and links to correct private action',async t=>{const {s,calls}=service(t);s.scope={...s.scope,adminKeyboard:true};let role='member';const original=s.ctx.helpers.httpRequest;s.ctx.helpers.httpRequest=async r=>r.url.endsWith('/getChatMember')?{ok:true,result:{status:role}}:original(r);const group={chat:{type:'supergroup',id:Number(c.allowedGroupId)},message_thread_id:10};await s.handle(message(40,'/menu',group));assert.equal(calls.filter(x=>x.method==='sendMessage').length,0);role='administrator';await s.handle(message(41,'/menu',group));const body=calls.at(-1).body;assert.equal(body.reply_markup.inline_keyboard[0][0].url,'https://t.me/N_N_A_TestBot?start=menu');assert.equal(body.message_thread_id,10);assert.equal(body.reply_parameters.message_id,41);await s.handle(message(42,'📄 User Chat History',group));assert.equal(calls.at(-1).body.reply_markup.inline_keyboard[0][0].url,'https://t.me/N_N_A_TestBot?start=history');const next=await s.handle(message(43,'/start history'));assert.equal(next.handled,false);assert.equal(next.event.message.text,'/history');});
