'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const {Api}=require('teleproto'),bigInt=require('big-integer');
const {runOperation}=require('../dist/nodes/NnaTelegramSender/sender');const {runReaction,getReactions,request}=require('../dist/nodes/NnaTelegramSender/reactions');
const c={apiId:12345,apiHash:'a'.repeat(32),sessionString:'1'+'A'.repeat(352),expectedUserId:'12345',allowedGroupId:'-1009876543',allowedGroupUsername:'example_group',allowedTopicIds:'10,20'};
const p={reactionSourceUrl:'https://t.me/c/7654321/35',reactionTargetUrl:'https://t.me/c/7654321/36',reactionGroupId:'-1007654321',reactionOperatorIds:'12345,67890'};
const row=(id,reaction)=>({peerId:new Api.PeerUser({userId:bigInt(id)}),reaction});const thumb=()=>new Api.ReactionEmoji({emoticon:'👍'});
function fake(){let sent=0,own=[];const peerId=new Api.PeerChannel({channelId:bigInt(7654321)});const client={connect:async()=>{},destroy:async()=>{},getMe:async()=>new Api.User({id:bigInt(12345)}),getEntity:async()=>new Api.Channel({id:bigInt(7654321),megagroup:true,forum:true}),getInputEntity:async()=>new Api.InputPeerChannel({channelId:bigInt(7654321),accessHash:bigInt(1)}),getMessages:async()=>[35,36].map(id=>new Api.Message({id,peerId,message:'test',reactions:id===36&&own.length?new Api.MessageReactions({results:own.map(reaction=>new Api.ReactionCount({reaction,count:1}))}):undefined})),invoke:async r=>{
 if(r.className==='channels.GetFullChannel')return {fullChat:{defaultSendAs:new Api.PeerUser({userId:bigInt(12345)})}};
 if(r.className==='messages.GetMessageReactionsList')return {reactions:r.id===35?[row(67890,thumb())]:own.map(x=>row(12345,x))};
 if(r.className==='messages.SendReaction'){sent++;own=r.reaction;return {updates:[]};}throw Error('Unexpected request');}};
 return {client,get sends(){return sent;},set own(r){own=r;}};
}
test('reaction inspection reads exact group messages and does not react',async()=>{const f=fake();const r=await runOperation('inspectReactionCopy',c,p,{createClient:async()=>f.client});assert.equal(r.status,'ready');assert.equal(r.reaction.emoji,'👍');assert.deepEqual(r.sourceReactorIds,['67890']);assert.equal(f.sends,0);});
test('reaction copy verifies actual personal reactor and repeated calls are no-op',async()=>{const f=fake();const r=await runOperation('copyUserReaction',c,p,{createClient:async()=>f.client});assert.equal(r.status,'reacted');assert.equal(r.senderId,'12345');assert.equal(f.sends,1);assert.equal((await runOperation('copyUserReaction',c,p,{createClient:async()=>f.client})).status,'already_present');assert.equal(f.sends,1);});
test('private peer resolution can use existing dialogs without joining',async()=>{const f=fake();f.client.getEntity=async()=>{throw Error('missing cache');};f.client.getDialogs=async()=>[{entity:new Api.Channel({id:bigInt(7654321),megagroup:true,forum:true})}];assert.equal((await runOperation('inspectReactionCopy',c,p,{createClient:async()=>f.client})).status,'ready');});
test('scope mismatch or same source/target fails before networking',async()=>{for(const patch of [{reactionSourceUrl:'https://t.me/c/99999/35'},{reactionTargetUrl:p.reactionSourceUrl}]){let opened=false;await assert.rejects(runOperation('copyUserReaction',c,{...p,...patch},{createClient:async()=>{opened=true;return fake().client;}}));assert.equal(opened,false);}});
test('unrelated users reactions and ambiguous operator reactions never copy',async()=>{for(const rows of [[row(999,thumb())],[row(67890,thumb()),row(12345,new Api.ReactionEmoji({emoticon:'❤'}))]]){const f=fake();const invoke=f.client.invoke;f.client.invoke=async r=>r.className==='messages.GetMessageReactionsList'&&r.id===35?{reactions:rows}:invoke(r);await assert.rejects(runOperation('copyUserReaction',c,p,{createClient:async()=>f.client}),/NNA_/);assert.equal(f.sends,0);}});
test('default send-as channel cannot impersonate the personal reaction identity',async()=>{const f=fake(),invoke=f.client.invoke;f.client.invoke=async r=>r.className==='channels.GetFullChannel'?{fullChat:{defaultSendAs:new Api.PeerChannel({channelId:bigInt(5)})}}:invoke(r);await assert.rejects(runOperation('copyUserReaction',c,p,{createClient:async()=>f.client}),/SENDER_IS_NOT_PERSONAL/);assert.equal(f.sends,0);});
test('existing personal reactions are preserved and custom reaction IDs copied exactly',async()=>{const f=fake(),invoke=f.client.invoke;f.own=[thumb()];const custom=new Api.ReactionCustomEmoji({documentId:bigInt('1234567890123456789')});f.client.invoke=async r=>r.className==='messages.GetMessageReactionsList'&&r.id===35?{reactions:[row(67890,custom)]}:invoke(r);const result=await runOperation('copyUserReaction',c,p,{createClient:async()=>f.client});assert.equal(result.reaction.customEmojiId,'1234567890123456789');const after=await f.client.invoke(new Api.messages.GetMessageReactionsList({id:36}));assert.equal(after.reactions.length,2);});
test('post-send transport failures are unconfirmed and never automatically retried',async()=>{const f=fake(),invoke=f.client.invoke;let attempts=0;f.client.invoke=async r=>{if(r.className==='messages.SendReaction'){attempts++;throw Error('network');}return invoke(r);};await assert.rejects(runOperation('copyUserReaction',c,p,{createClient:async()=>f.client}),/REACTION_UNCONFIRMED/);assert.equal(attempts,1);});
test('reaction listing follows pagination and rejects repeated cursor',async()=>{let page=0;const rows=await getReactions({invoke:async()=>++page===1?{reactions:[row(999,thumb())],nextOffset:'next'}:{reactions:[row(67890,thumb())]}},{},35,x=>x);assert.equal(rows.length,2);await assert.rejects(getReactions({invoke:async()=>({reactions:[],nextOffset:'same'})},{},35,x=>x),/CURSOR_STALLED/);});
test('empty target skips Telegram invalid empty-list RPC and verifies after first reaction',async()=>{
 const f=fake(),invoke=f.client.invoke;let targetReads=0;
 f.client.invoke=async r=>{if(r.className==='messages.GetMessageReactionsList'&&r.id===36){targetReads++;if(!f.sends)throw Error('MSG_ID_INVALID');}return invoke(r);};
 assert.equal((await runOperation('inspectReactionCopy',c,p,{createClient:async()=>f.client})).status,'ready');assert.equal(targetReads,0);
 assert.equal((await runOperation('copyUserReaction',c,p,{createClient:async()=>f.client})).status,'reacted');assert.equal(targetReads,1);assert.equal(f.sends,1);
});
test('nonempty target listing error never becomes permission to overwrite existing reactions',async()=>{
 const f=fake(),invoke=f.client.invoke;f.own=[new Api.ReactionEmoji({emoticon:'❤'})];
 f.client.invoke=async r=>{if(r.className==='messages.GetMessageReactionsList'&&r.id===36)throw Error('MSG_ID_INVALID');return invoke(r);};
 await assert.rejects(runOperation('copyUserReaction',c,p,{createClient:async()=>f.client}),/REACTION_CHECK_FAILED/);assert.equal(f.sends,0);
});
