'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path');
const {Service}=require('../dist/nodes/NnaMediaCollection/core');
const {Store}=require('../dist/nodes/NnaMediaCollection/store');
const creds={apiId:1,apiHash:'a'.repeat(32),sessionString:'1fake',expectedUserId:'42',allowedGroupId:'-1001234500000',allowedGroupUsername:'examplegroup',allowedTopicIds:'10'};
const scope={groupId:'-1001234500000',botUsername:'example_bot',operatorIds:['42','43'],topicIds:[10],analysisCommand:'mediareport',adminCommandGroupIds:['-1001234500000']};
const input=(id,extra={})=>({update_id:id,message:{message_id:id,date:Math.floor(Date.now()/1000),chat:{id:42,type:'private'},from:{id:42,is_bot:false},...extra}});
const photo={photo:[{file_id:'image',file_unique_id:'image-unique',file_size:100}]},video={video:{file_id:'video',file_unique_id:'video-unique',file_size:300,mime_type:'video/mp4',duration:5}};
function setup(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'nna-report-test-'));t.after(()=>{assert.equal(path.dirname(root),os.tmpdir());assert(path.basename(root).startsWith('nna-report-test-'));fs.rmSync(root,{recursive:true,force:true});});const s=new Service({},creds,{},scope,{root});s.me={id:99,is_bot:true,username:'example_bot'};s.store=new Store(99,root);s.calls=[];s.bot=async(method,body)=>{s.calls.push({method,body});return method==='getChatMember'?{status:'administrator',user:{id:42}}:{message_id:500};};s.jobs=[];s.analyze=async d=>{s.jobs.push(d);return {json:{next:d.mime.startsWith('image/')?1:2,jobKey:d.key,revision:d.rev},binary:{data:{data:'ZmFrZQ=='}}};};return s;}
test('ordinary messages, media and poll callbacks pass unchanged without analysis',async t=>{const s=setup(t);for(const u of [input(1,{text:'/poll'}),input(2,photo),input(3,{text:'/analyze'}),{update_id:4,callback_query:{data:'ps:42:rev:confirm',from:{id:42},message:{chat:{id:42,type:'private'}}}}]){const r=await s.handleAnalysis(u);assert.equal(r.json.analysisHandled,false);assert.deepEqual(r.json.event,u);}assert.equal(s.calls.length,0);assert.equal(s.jobs.length,0);});

test('failed report retry help retains the reply bot command after editing progress',async t=>{const s=setup(t);await s.handleAnalysis(input(1,{text:'/mediareport'}));await s.handleAnalysis(input(2,photo));const d=s.jobs[0];s.store.change(d.key,x=>({...x,controlId:500}));assert.equal((await s.finish(d.key,d.rev,{})).status,'analysis_failed');const edited=s.calls.find(c=>c.method==='editMessageText');assert(edited);assert.match(edited.body.text,/\/mediareport\b/);assert.doesNotMatch(edited.body.text,/\/analyze\b/);});
test('distinct command/button arms one image or video, preserves binary and blocks replay',async t=>{for(const [label,media,next] of [['/mediareport',photo,1],['🔎 Image / Video Report',video,2],['/start mediareport',photo,1]]){const s=setup(t);assert.equal((await s.handleAnalysis(input(1,{text:label}))).json.status,'report_armed');const r=await s.handleAnalysis(input(2,media));assert.equal(r.json.next,next);assert.equal(r.json.analysisHandled,true);assert(r.binary.data);assert.equal(s.jobs[0].analysisOnly,true);assert.equal((await s.handleAnalysis(input(2,media))).json.status,'duplicate_report');assert.equal((await s.handleAnalysis(input(3,photo))).json.analysisHandled,false);assert.equal(s.jobs.length,1);}});
test('reply targets exact old video and never posts media or asks for a destination',async t=>{const s=setup(t),u=input(2,{text:'/mediareport@example_bot',reply_to_message:{message_id:1,from:{id:42,is_bot:false},...video}});assert.equal((await s.handleAnalysis(u)).json.next,2);assert.equal(s.jobs[0].sourceMessageId,1);assert.equal((await s.handleAnalysis(u)).json.status,'duplicate_report');assert.equal(s.jobs.length,1);const d=s.jobs[0];const raw={summaryLines:['The artwork shows a lamp.','Soft light fills the scene.','The mood is calm and peaceful.'],candidates:['Peace','Light','Spirituality'].map(tag=>({tag,confidence:.9,evidence:'Sample'}))};assert.equal((await s.finish(d.key,d.rev,raw)).status,'analysis_ready');const b=s.calls.at(-1).body;assert.equal(b.entities.length,2);assert.deepEqual(b.reply_markup.inline_keyboard,[]);assert(!b.text.includes('topic'));});
test('other slash command clears armed report without consuming the other feature',async t=>{const s=setup(t);await s.handleAnalysis(input(1,{text:'/mediareport'}));const u=input(2,{text:'/poll'});assert.deepEqual((await s.handleAnalysis(u)).json.event,u);assert.equal((await s.handleAnalysis(input(3,photo))).json.analysisHandled,false);assert.equal(s.jobs.length,0);});
test('distinct cancel stops pending AI and late completion cannot send a result',async t=>{const s=setup(t);await s.handleAnalysis(input(1,{text:'/mediareport'}));await s.handleAnalysis(input(2,photo));const d=s.jobs[0];assert.equal((await s.handleAnalysis(input(3,{text:'/cancelmedia'}))).json.status,'report_cancelled');assert.equal((await s.finish(d.key,d.rev,{})).status,'stale_analysis');assert.equal(s.store.read(d.key).status,'cancelled');});
test('foreign reply media, stale identity, forwarded commands and other bot mentions cannot analyze',async t=>{const s=setup(t);await s.handleAnalysis(input(1,{text:'/mediareport',reply_to_message:{message_id:10,from:{id:43},...photo}}));assert.equal(s.jobs.length,0);await s.handleAnalysis(input(2,{text:'/mediareport',forward_origin:{type:'user'}}));assert.equal(s.store.read('report_mode_42'),null);assert.equal((await s.handleAnalysis(input(3,{text:'/mediareport@other_bot'}))).json.analysisHandled,false);await assert.rejects(s.handleAnalysis(input(4,{text:'/mediareport',date:1})),/STALE_INPUT/);});
test('group command responds with a report-specific private deep link and never analyzes group media',async t=>{const s=setup(t),r=await s.handleAnalysis(input(1,{text:'/mediareport',chat:{id:-1001234500000,type:'supergroup'},is_topic_message:true,message_thread_id:10}));assert.equal(r.json.status,'group_menu');assert.equal(s.calls.at(-1).body.reply_markup.inline_keyboard[0][0].url,'https://t.me/example_bot?start=mediareport');assert.equal(s.jobs.length,0);});
test('report command registration preserves existing reply bot command menus',async t=>{const s=setup(t),menus=new Map();s.bot=async(method,b)=>{const key=JSON.stringify(b.scope);if(method==='getMyCommands')return menus.get(key)||[{command:'poll',description:'Poll'}];if(method==='setMyCommands')menus.set(key,b.commands);return true;};await s.configureAnalysisCommands();for(const value of menus.values())assert.deepEqual(value.map(c=>c.command),['poll','mediareport','cancelmedia']);});
